//DTO dat atransfer object
//class name should stat with upper case
class IssuedBook{
    _id;//autogenerated id
    name;
    genre;
    price;
    publisher;
    issuedBy;
    issueDate;
    returnDate;



    //obj1 = obj2 we can  also do like this but the problem is obj2 addresed 
    //is passed to obj1 whenever we made any changes in one obj the other will effect
//whenever we create object the constructore is automatically invoked =  parameterized constructor
constructor(user){
    this._id=user.IssuedBook._id;
    this.name=user.IssuedBook.name;
    this.genre=user.IssuedBook.genre;
    this.price=user.IssuedBook.price;
    this.publisher=user.IssuedBook.publisher;
    this.issuedBy=user.IssuedBook.issuedBy;
    this.issueDate=user.IssuedBook.issueDate;
    this.returnDate=user.IssuedBook.returnDate;
}
}
module.exports=IssuedBook;